image: docker:20

variables:
  IMAGE_TAG: chainfusion/landing:$CI_COMMIT_REF_NAME
  IMAGE_TAG_LATEST: chainfusion/landing:latest

stages:
  - build
  - deploy

.docker_build_template:
  services:
    - docker:20-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

.deploy-template:
  image: crosscone/k8s-gcloud:latest
  script:
    - configure
    - helm upgrade --install --wait $CHART_NAME ./chart
        --set image=$IMAGE_TAG
        --set replicas=$REPLICAS
        --set hostname=$HOSTNAME
        --set tls.enabled=true
        --set tls.secretName=$TLS_SECRET_NAME
        --set redirect.hostname=$REDIRECT_HOSTNAME
        --set redirect.tls.enabled=true
        --set redirect.tls.secretName=$REDIRECT_TLS_SECRET_NAME

build-mr:
  stage: build
  only:
    - merge_requests
  image: node:16
  script:
    - yarn
    - yarn build

build-main:
  stage: build
  only:
    - main
  extends: .docker_build_template
  script:
    - docker build -t $IMAGE_TAG_LATEST .
    - docker push $IMAGE_TAG_LATEST

build-tags:
  stage: build
  only:
    - tags
  extends: .docker_build_template
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:dev:
  stage: deploy
  only:
    - tags
  extends: .deploy-template
  variables:
    CHART_NAME: chainfusion-landing-dev
    REPLICAS: 1
    HOSTNAME: dev.chainfusion.org
    TLS_SECRET_NAME: chainfusion-org-tls

deploy:prod:
  stage: deploy
  only:
    - tags
  extends: .deploy-template
  when: manual
  variables:
    CHART_NAME: chainfusion-landing
    REPLICAS: 1
    HOSTNAME: chainfusion.org
    TLS_SECRET_NAME: chainfusion-org-tls