apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{ end }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: http
  {{ if .Values.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.tls.secretName }}
  {{ end }}